packageList:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
keyUrl:
  - https://download.docker.com/linux/ubuntu/gpg
repoUrl:
  - https://download.docker.com/linux/ubuntu
dockerVersion: 5:18.09.5~3-0~ubuntu
dockerPackages:
  - docker-ce-cli={{ dockerVersion }}-{{ hostvars[inventory_hostname].ansible_distribution_release }}
  - docker-ce={{ dockerVersion }}-{{ hostvars[inventory_hostname].ansible_distribution_release }}
  - containerd.io
dockerUsers:
  - nic
